### ISSUE TITLE
On load crash

### ISSUE THREAD

**Issue by ZeroFategod** [StrayWolfe/Cooking-with-TFC#10]
playing a small pack of TFC and other addons tried to add yours and it crashed on startup

 ---- Minecraft Crash Report ----
// Don't be sad, have a hug! <3

Time: 4/26/17 4:26 PM
Description: There was a severe problem during mod loading that has caused the game to fail

cpw.mods.fml.common.LoaderException: java.lang.NoClassDefFoundError: terramisc/core/TFCMBlocks
	at cpw.mods.fml.common.LoadController.transition(LoadController.java:163)
	at cpw.mods.fml.common.Loader.initializeMods(Loader.java:739)
	at cpw.mods.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:311)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:552)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:878)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.NoClassDefFoundError: terramisc/core/TFCMBlocks
	at straywolfe.cookingwithtfc.common.registries.CWTFCRegistries.registerRecipes(CWTFCRegistries.java:119)
	at straywolfe.cookingwithtfc.common.registries.CWTFCRegistries.setupRegistries(CWTFCRegistries.java:44)
	at straywolfe.cookingwithtfc.common.CookingWithTFC.init(CookingWithTFC.java:78)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532)
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
	at cpw.mods.fml.common.Loader.initializeMods(Loader.java:737)
	... 10 more
Caused by: java.lang.ClassNotFoundException: terramisc.core.TFCMBlocks
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 39 more
Caused by: java.lang.NullPointerException
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
	... 41 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_111, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 206664536 bytes (197 MB) / 1352138752 bytes (1289 MB) up to 10737418240 bytes (10240 MB)
	JVM Flags: 3 total; -Xms256M -Xmx11520M -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1558 39 mods loaded, 39 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHI	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHI	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1558-1.7.10-universal.jar) 
	UCHI	Forge{10.13.4.1558} [Minecraft Forge] (forge-1.7.10-10.13.4.1558-1.7.10-universal.jar) 
	UCHI	tfc_coremod{0.79.27} [TFC[coremod]] (minecraft.jar) 
	UCHI	CodeChickenCore{1.0.7.46} [CodeChicken Core] (minecraft.jar) 
	UCHI	itemphysic{1.1.5} [ItemPhysic] (minecraft.jar) 
	UCHI	NotEnoughItems{1.0.5.110} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.5.110-universal.jar) 
	UCHI	PlayerAPI{1.4} [Player API] (minecraft.jar) 
	UCHI	RenderPlayerAPI{1.4} [Render Player API] (minecraft.jar) 
	UCHI	SmartCore{1.0.3} [Smart Core] (minecraft.jar) 
	UCHI	terrafirmacraft{0.79.27} [TerraFirmaCraft] ([1.7.10]TerraFirmaCraft-0.79.27.903.jar) 
	UCHI	tfcadditions{@MODVERSION@} [TFC-Additions] ([1.7.10][0.79.23+]TFC-Additions-1.0.3.jar) 
	UCHI	DecorationsTFC{1.0.20} [Decorations] ([1.7.10]Decorations-1.0.20.jar) 
	UCHI	lwstfc{3.9.B79} [Leather Water Sac] ([1.7.10]LeatherWaterSac-3.9.B79.jar) 
	UCHI	tfcm{0.9.1} [TerraMisc] ([1.7.10]TerraMisc-0.9.1.jar) 
	UCHI	tfccellars{1.010} [CellarsAddon] ([1.7.10]TFCCellarsAddon-1.010.jar) 
	UCHI	tfcudarymod{0.2.30} [TFC Udary Mod] ([1.7.10]TFCUdaryMod-0.2.30.jar) 
	UCHI	animalcrate{0.01} [AnimalCrate] (animalcrate-0.1.jar) 
	UCHE	cookingwithtfc{0.0.7.0} [Cooking with TFC] (CookingWithTFC-1.7.10-0.0.7.0.jar) 
	UCHI	DynamicLights{1.3.9} [Dynamic Lights] (DynamicLights-1.7.10.jar) 
	UCHI	DynamicLights_onFire{1.0.5} [Dynamic Lights Burning Entity Module] (DynamicLights-1.7.10.jar) 
	UCHI	DynamicLights_creepers{1.0.4} [Dynamic Lights Creeper Module] (DynamicLights-1.7.10.jar) 
	UCHI	DynamicLights_dropItems{1.0.8} [Dynamic Lights EntityItem Module] (DynamicLights-1.7.10.jar) 
	UCHI	DynamicLights_entityClasses{1.0.1} [Dynamic Lights Entity Light Module] (DynamicLights-1.7.10.jar) 
	UCHI	DynamicLights_mobEquipment{1.0.8} [Dynamic Lights Mob Equipment Light Module] (DynamicLights-1.7.10.jar) 
	UCHI	DynamicLights_flameArrows{1.0.0} [Dynamic Lights Fiery Arrows Light Module] (DynamicLights-1.7.10.jar) 
	UCHI	DynamicLights_floodLights{1.0.2} [Dynamic Lights Flood Light] (DynamicLights-1.7.10.jar) 
	UCHI	DynamicLights_otherPlayers{1.0.8} [Dynamic Lights OtherPlayers Light Module] (DynamicLights-1.7.10.jar) 
	UCHI	DynamicLights_thePlayer{1.1.4} [Dynamic Lights Player Light Module] (DynamicLights-1.7.10.jar) 
	UCHI	FastCraft{1.21} [FastCraft] (fastcraft-1.21.jar) 
	UCHI	journeymap{@JMVERSION@} [JourneyMap] (journeymap-1.7.10-5.1.0-unlimited.jar) 
	UCHI	sciapi{0.5.2} [SciAPI] (SciAPI v0.5.2.jar) 
	UCHI	SmartMoving{15.6} [Smart Moving] (SmartMoving-1.7.10-15.6.jar) 
	UCHI	SmartRender{2.1} [Smart Render] (SmartRender-1.7.10-2.1.jar) 
	UCHI	stellarsky{0.1.15} [Stellar Sky] (Stellar Sky-v0.1.15[1.7.10].jar) 
	UCHI	TerraFirmaCraftNEIplugin{1.5.3.24} [TerraFirmaCraftNEIplugin] (TerraFirmaCraftNEIplugin-1.7.10-1.5.3.24.jar) 
	UCHI	TooMuchTime{2.4.0} [TooMuchTime] (TooMuchTime-1.7.10-2.4.0.tnfc-4-universal.jar) 
	UCHI	AS_UpdateCheck{1.1.7} [AtomicStryker Update Check Mod] (UpdateCheckerMod-1.7.10.jar) 
	UCHI	Waila{1.5.10} [Waila] (Waila-1.5.10_1.7.10.jar) 
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.5.0 NVIDIA 378.92' Renderer: 'GeForce GTX 770/PCIe/SSE2'

**Comment by StrayWolfe** [comment]
This is crash happens because Terramisc 0.9.1 does not have the fruit press yet, update to a current version of Terramisc and this will not happen.
