### ISSUE TITLE
Crash when eating venison stew

### ISSUE THREAD

**Issue by TestSubject45** [StrayWolfe/Cooking-with-TFC#9]
I was able to make venison stew and pick it up in a bowl, but the game threw a ArrayOutOfBounds error and crashed when I tried to eat it.  

```
---- Minecraft Crash Report ----
// I just don't know what went wrong :(

Time: 4/23/17 2:08 PM
Description: Ticking player

java.lang.ArrayIndexOutOfBoundsException: 4
	at straywolfe.cookingwithtfc.common.item.ItemTFCMealTransform.getNutritionalWeights(ItemTFCMealTransform.java:218)
	at straywolfe.cookingwithtfc.common.item.ItemTFCMealTransform.func_77654_b(ItemTFCMealTransform.java:165)
	at net.minecraft.item.ItemStack.func_77950_b(ItemStack.java:151)
	at net.minecraft.entity.player.EntityPlayer.func_71036_o(EntityPlayer.java:419)
	at net.minecraft.entity.player.EntityPlayerMP.func_71036_o(EntityPlayerMP.java:866)
	at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:242)
	at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:295)
	at net.minecraft.network.NetHandlerPlayServer.func_147347_a(NetHandlerPlayServer.java:303)
	at net.minecraft.network.play.client.C03PacketPlayer.func_148833_a(SourceFile:137)
	at net.minecraft.network.play.client.C03PacketPlayer.func_148833_a(SourceFile:8)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at straywolfe.cookingwithtfc.common.item.ItemTFCMealTransform.getNutritionalWeights(ItemTFCMealTransform.java:218)
	at straywolfe.cookingwithtfc.common.item.ItemTFCMealTransform.func_77654_b(ItemTFCMealTransform.java:165)
	at net.minecraft.item.ItemStack.func_77950_b(ItemStack.java:151)
	at net.minecraft.entity.player.EntityPlayer.func_71036_o(EntityPlayer.java:419)
	at net.minecraft.entity.player.EntityPlayerMP.func_71036_o(EntityPlayerMP.java:866)
	at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:242)

-- Player being ticked --
Details:
	Entity Type: null (net.minecraft.entity.player.EntityPlayerMP)
	Entity ID: 16
	Entity Name: [REDACTED]
	Entity's Exact location: 39015.81, 145.00, -8048.20
	Entity's Block location: World: (39015,145,-8049), Chunk: (at 7,9,15 in 2438,-504; contains blocks 39008,0,-8064 to 39023,255,-8049), Region: (76,-16; contains chunks 2432,-512 to 2463,-481, blocks 38912,0,-8192 to 39423,255,-7681)
	Entity's Momentum: 0.00, -0.08, 0.00
Stacktrace:
	at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:295)
	at net.minecraft.network.NetHandlerPlayServer.func_147347_a(NetHandlerPlayServer.java:303)
	at net.minecraft.network.play.client.C03PacketPlayer.func_148833_a(SourceFile:137)
	at net.minecraft.network.play.client.C03PacketPlayer.func_148833_a(SourceFile:8)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)

-- Ticking connection --
Details:
	Connection: net.minecraft.network.NetworkManager@3767e84d
Stacktrace:
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_111, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 6847725368 bytes (6530 MB) / 7516192768 bytes (7168 MB) up to 7516192768 bytes (7168 MB)
	JVM Flags: 5 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms7168m -Xmx7168m -XX:+UseG1GC -XX:MaxGCPauseMillis=4
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 13, allocated: 0, tallocated: 0
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1614 16 mods loaded, 16 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{7.10.99.99} [Forge Mod Loader] (modpack.jar) 
	UCHIJAAAA	Forge{10.13.4.1614} [Minecraft Forge] (modpack.jar) 
	UCHIJAAAA	tfc_coremod{0.79.29} [TFC[coremod]] (minecraft.jar) 
	UCHIJAAAA	CodeChickenCore{1.0.7.47} [CodeChicken Core] (minecraft.jar) 
	UCHIJAAAA	NotEnoughItems{1.0.5.120} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.5.120-universal.jar) 
	UCHIJAAAA	terrafirmacraft{0.79.29} [TerraFirmaCraft] ([1.7.10]TerraFirmaCraft-0.79.29.922.jar) 
	UCHIJAAAA	tfccellars{1.1} [CellarsAddon] ([1.7.10]TFCCellarsAddon-1.1.jar) 
	UCHIJAAAA	fitw{1.2.1} [FingerInTheWind] ([TFC-79.28]FingerInTheWind-1.2.1.jar) 
	UCHIJAAAA	BiblioCraft{1.11.5} [BiblioCraft] (BiblioCraft-Mod-1.7.10.jar) 
	UCHIJAAAA	BiblioWoodsTFC{1.2} [BiblioWoodsTFC] (BiblioWoods[TerraFirmaCraftV0.79.23][v1.2].jar) 
	UCHIJAAAA	cookingwithtfc{0.0.7.0} [Cooking with TFC] (CookingWithTFC-1.7.10-0.0.7.0.jar) 
	UCHIJAAAA	multimine{1.5.4port1710} [Multi Mine] (MultiMine-1.7.10.jar) 
	UCHIJAAAA	ReiMinimap{1.7.10} [Rei's Minimap] (Reis-Minimap-Mod-1.7.10.jar) 
	UCHIJAAAA	TerraFirmaCraftNEIplugin{1.5.3.25} [TerraFirmaCraftNEIplugin] (TerraFirmaCraftNEIplugin-1.7.10-1.5.3.25.jar) 
	UCHIJAAAA	AS_UpdateCheck{1.1.7} [AtomicStryker Update Check Mod] (UpdateCheckerMod-1.7.10.jar) 
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Player Count: 1 / 8; [EntityPlayerMP['zebede5'/16, l='4546456', x=39015.81, y=145.00, z=-8048.20]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'`
```

**Comment by StrayWolfe** [comment]
Should be resolved with latest update
